// GENERATED by scripts/build-core.js from core/index.js — edit core/, not this copy.
'use strict';

/**
 * Shared pure decision core — single canonical source.
 *
 * Vendored into `github-action/src/shared/core/` and
 * `plugin/src/shared/core/` by `scripts/build-core.js` (consumers stay
 * self-contained; no cross-runtime imports at runtime). The OpenChamber
 * status bundle imports `core/routing.js` directly (bundled at build
 * time). Edit `core/`, never the vendored copies — CI fails on drift.
 */

module.exports = {
  ...require('./model-ref'),
  ...require('./free-quota'),
  ...require('./probe'),
  ...require('./budget'),
  ...require('./lookup'),
  ...require('./routing'),
};
