#!/usr/bin/env node
'use strict';

/**
 * Vendor `core/*.js` into every runtime consumer.
 *
 * Usage:
 *   node scripts/build-core.js           # write vendored copies
 *   node scripts/build-core.js --check   # exit 1 on drift (CI guard)
 *
 * Destinations (committed; consumers stay self-contained, no
 * cross-runtime imports at runtime):
 *   github-action/src/shared/core/   (fail-closed CI action)
 *   plugin/src/shared/core/          (fail-soft OpenCode plugin)
 *
 * Each vendored file is prefixed with a GENERATED banner; byte-compare is
 * done against the same built output, so edit `core/` — never a copy.
 */

const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');
const SRC = path.join(ROOT, 'core');
const DESTS = [
  path.join(ROOT, 'github-action', 'src', 'shared', 'core'),
  path.join(ROOT, 'plugin', 'src', 'shared', 'core'),
];

const check = process.argv.includes('--check');

const files = fs
  .readdirSync(SRC)
  .filter((f) => f.endsWith('.js'))
  .sort();

if (!files.length) {
  console.error('build-core: no files found in core/');
  process.exit(1);
}

const drifted = [];

for (const dest of DESTS) {
  fs.mkdirSync(dest, { recursive: true });
  for (const file of files) {
    const source = fs.readFileSync(path.join(SRC, file), 'utf8');
    const built =
      `// GENERATED by scripts/build-core.js from core/${file} — edit core/, not this copy.\n` +
      source;
    const target = path.join(dest, file);
    const existing = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : null;
    if (existing === built) continue;
    if (check) {
      drifted.push(path.relative(ROOT, target));
    } else {
      fs.writeFileSync(target, built);
      console.log(`build-core: wrote ${path.relative(ROOT, target)}`);
    }
  }
}

if (check) {
  if (drifted.length) {
    console.error('build-core: vendored core copies are stale:');
    for (const d of drifted) console.error(`  ${d}`);
    console.error('run: node scripts/build-core.js (or: mise run build-core)');
    process.exit(1);
  }
  console.log(`build-core: ${files.length} files x ${DESTS.length} destinations in sync.`);
} else {
  console.log(`build-core: done (${files.length} files x ${DESTS.length} destinations).`);
}
