// GENERATED by scripts/build-core.js from core/probe.js — edit core/, not this copy.
'use strict';

/**
 * Free-availability probe + Go usage-window classifiers — shared pure
 * decision core (no dependencies).
 *
 * Vendored into `github-action/src/shared/core/` and
 * `plugin/src/shared/core/` by `scripts/build-core.js`; edit `core/`,
 * never the vendored copies.
 *
 * Extracted verbatim from the fail-closed GitHub Action (policy lives in
 * the caller: the action keeps all fetch/polling/outputs code).
 */

function pickKey(obj, names) {
  for (const n of names) {
    if (obj && obj[n] !== undefined && obj[n] !== null) return obj[n];
  }
  return undefined;
}

function secondsUntil(iso) {
  const t = Date.parse(iso);
  if (!Number.isFinite(t)) return null;
  return Math.max(0, Math.round((t - Date.now()) / 1000));
}

// Normalize the several wire shapes seen for GET /zen/go/v1/usage into
// [{ name, percent, resetSec, status }]. Shapes handled:
//   { usage: { rolling, weekly, monthly: { status, percent|usagePercent, resetsAt|resetInSec } } }
//   { useBalance, rollingUsage, weeklyUsage, monthlyUsage: { status, usagePercent, resetInSec } }
//   { rolling, weekly, monthly } / { windows: { rolling, weekly, monthly } }
function parseGoUsageWindows(data) {
  if (!data || typeof data !== 'object') return null;
  const root = data.usage && typeof data.usage === 'object' ? data.usage : data;
  const bag =
    (root.windows && typeof root.windows === 'object' ? root.windows : null) || root;
  const candidates = [
    ['rolling', bag.rolling ?? bag.rollingUsage],
    ['weekly', bag.weekly ?? bag.weeklyUsage],
    ['monthly', bag.monthly ?? bag.monthlyUsage],
  ];
  const windows = [];
  for (const [name, w] of candidates) {
    if (!w || typeof w !== 'object') continue;
    const rawPercent = pickKey(w, ['usagePercent', 'percent', 'usage_percent', 'usagePct']);
    const percent =
      typeof rawPercent === 'number' && Number.isFinite(rawPercent) ? rawPercent : null;
    const rawReset = pickKey(w, [
      'resetInSec',
      'resetsInSec',
      'reset_in_sec',
      'resets_in_seconds',
      'resetsInSeconds',
    ]);
    const rawAt = pickKey(w, ['resetsAt', 'resetAt', 'reset_at', 'resets_at']);
    const resetSec =
      typeof rawReset === 'number' && Number.isFinite(rawReset)
        ? rawReset
        : typeof rawAt === 'string'
          ? secondsUntil(rawAt)
          : null;
    const status =
      typeof w.status === 'string' ? w.status.toLowerCase() : null;
    windows.push({ name, percent, resetSec, status });
  }
  return windows.length ? windows : null;
}

function goWindowsExhausted(windows) {
  const blocked = new Set(['limited', 'exhausted', 'blocked', 'rate_limited', 'denied']);
  return windows.some(
    (w) =>
      (w.percent !== null && w.percent >= 100) ||
      (w.status !== null && blocked.has(w.status)),
  );
}

function isSessionGate(text) {
  const t = String(text ?? '').toLowerCase();
  return t.includes('missingsessionid') || t.includes('only be used in opencode');
}

// Classify one free-probe answer into a state:
//   available  2xx: the model answered.
//   selectable 400 + session gate: the key is accepted and the free route
//              exists, but Zen only serves free models to OpenCode clients,
//              so a raw probe can never get a completion. The model is still
//              usable by the downstream OpenCode step.
//   exhausted  402/429/503/529: free quota spent.
//   unavailable 403/404: forbidden or removed.
//   authFailed 401: the key is rejected here.
//   unknown    anything else (500s, network errors, unexpected 400s).
function classifyFreeProbe({ status, text, error }) {
  if (status === null) return { state: 'unknown', reason: `free probe unreachable (${error})` };
  if (status >= 200 && status < 300) return { state: 'available', reason: 'free probe succeeded' };
  if (status === 401) {
    return { state: 'authFailed', reason: 'free rejected (401): token invalid for free probe' };
  }
  if (status === 402 || status === 429 || status === 503 || status === 529) {
    return { state: 'exhausted', reason: `free exhausted (HTTP ${status})` };
  }
  if (status === 403 || status === 404) {
    return { state: 'unavailable', reason: `free unavailable (HTTP ${status})` };
  }
  if (status === 400 && isSessionGate(text)) {
    return { state: 'selectable', reason: 'free usable via OpenCode (session-gated probe)' };
  }
  return { state: 'unknown', reason: `free probe HTTP ${status}` };
}

module.exports = {
  parseGoUsageWindows,
  goWindowsExhausted,
  isSessionGate,
  classifyFreeProbe,
};
